name: Unified_Data_Update

on:
  schedule:
    - cron: '15 0,12,11,23 * * *'
    #- cron: '0 6,18 * * *'
  workflow_dispatch:
    inputs:
      name:
        required: false
        default: "No"
        description: 'name'

jobs:
  run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.7]
        R-version: [ '4.0.5' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install ipython
        if [ -f state_data/requirements.txt ]; then cd state_data/ && pip install -r requirements.txt; fi
    - name: Install R Lib
      run: |
        R --version
        zip -s 0 my_r_lib.zip --out unsplit.zip
        sudo unzip -o unsplit.zip -d /
        sudo apt-get install libcurl4-openssl-dev r-base
        R --version
        sudo Rscript -e "install.packages('curl',dependencies=TRUE)"
        sudo Rscript -e "library(EpiEstim)"
    - name: Run unified scripts
      run: |
        cd state_data/ && ipython3 colab_unified_states_metrics.py && cd ../
    - name: Get New Files
      run: |
        git status -uno
    - uses: EndBug/add-and-commit@v7
      with:
        add: state_data/allmetrics_states.csv state_data/allmetrics_states.json state_data/rt_graph.json state_data/test.json
        author_name: GithubActions States Update
        author_email: covidtodayindia@gmail.com
        message: 'States Data Updated'
    - name: Run unified scripts
      run: |
        cd district_data/ && ipython3 colab_unified_districts_metrics.py && cd ../
      run: |
        git status -uno
    - uses: EndBug/add-and-commit@v7
      with:
        add: district_data/test.json district_data/rt_temp/rtoutput.csv district_data/rt_graph.json district_data/allmetrics_districts.json district_data/allmetrics_districts.csv
        author_name: GithubActions States Update
        author_email: covidtodayindia@gmail.com
        message: 'District Data Updated'
    - name: Run unified scripts
      run: |
        cd state_data/ && python3 state_vaccine.py && cd ../
        #cd mobility-index/ && python Mobility_indices.py cd ../
    - name: Get New Files
      run: |
        git status -uno
    - uses: EndBug/add-and-commit@v7
      with:
        add: state_data/rt_temp/rtoutput.csv state_data/state_vaccine.json
        author_name: GithubActions States Update
        author_email: covidtodayindia@gmail.com
        message: 'States Vaccine Data Updated'
